### PR TITLE
GH-21: Add optinal variant support to pattern preview.

### LINKED ISSUE #21: Make sure we can indicate which variant to render on `/pattern-preview`
This is a follow up of #15, its scope is to support an optional `variant` URL parameter that would indicate which variant of the given pattern we want to render.

### PR DESCRIPTION
**Pull request by ademarco**

### CODE REVIEW

**Comment by ademarco** [comment]
To test check [this README section](https://github.com/international-labour-organization/ilo_base_theme/blob/GH-21-variant/README.md#render-patterns-on-demand) and try to render a pattern with and without variants, cards is a good candidate.

**Comment by justintemps** [comment]
@bashlk can you test this please?

**Comment by Shashika6** [comment]
Hey @ademarco I tested out the variants and it seems to be working fine.

Screenshot 2024-06-29 at 22 40 08

* **However I noticed that there are issues in spacing now of the corners in all components like button accordions etc any idea why this is happening.**


Screenshot 2024-06-29 at 22 40 08

**Comment by ademarco** [comment]
We will need to follow up the style issue in another ticket, as it's out of scope of this one.

**Pull request merged**
